name: connectedturtle_website
description: A pure client-side app without ssr.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.9.0
  jaspr_router: ^0.3.0
  intl: ^0.17.0
  intl_utils: ^2.8.4
  land: ^0.0.7
  js: ^0.6.7
  dartgsap:
    path: ../dartgsap
  
dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.5+5
  #build_web_compilers: ^4.0.5
  lints: ^2.1.0
  sass_dart_compiler:
    path: ../sass_dart_compiler

jaspr:
  uses-ssr: false

